{
  "alarms" : [

    {
      "identifier" : "CHRONOS_PROC_FAIL_CLEAR",
      "index" : 3000,
      "severity" : "CLEARED",
      "cause" : "SOFTWARE_ERROR",
      "description" : "Chronos: Process failure cleared",
      "details" : "The Chronos process has been restored to normal operation."
    },

    {
      "identifier" : "CHRONOS_PROC_FAIL_MAJOR",
      "index" : 3000,
      "severity" : "MAJOR",
      "cause" : "SOFTWARE_ERROR",
      "description" : "Chronos: Process failure",
      "details" : "Monit has detected that the Chronos process has failed. A restart will automatically be attempted. If this alarm does not clear, the Chronos process may have been stopped or an unrecoverable failure may have occurred."
    },


    {
      "identifier" : "CHRONOS_TIMER_POP_ERROR_CLEAR",
      "index" : 3001,
      "severity" : "CLEARED",
      "cause" : "UNDERLAYING_RESOURCE_UNAVAILABLE",
      "description" : "Chronos: Timer pop error cleared",
      "details" : "Chronos local timer delivery restored to normal operation."
    },

    {
      "identifier" : "CHRONOS_TIMER_POP_ERROR_MAJOR",
      "index" : 3001,
      "severity" : "MAJOR",
      "cause" : "UNDERLAYING_RESOURCE_UNAVAILABLE",
      "description" : "Chronos: Timer pop error",
      "details" : "Chronos was unable to pop a timer on the last replica due to a local delivery error. If this alarm does not clear, the local Chronos client cannot be contacted and may have failed."
    }

  ]
}


